name: Build and deploy ASP.Net Core app to Azure Web App - BasecampWizardy

on:
  push:
    branches:
      - main
      - master  # Add master branch here
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      # ... rest of your build steps ...

deploy:
  runs-on: windows-latest
  needs: build
  environment:
    name: 'Production'
    url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: .net-app


update_documentation:
    runs-on: windows-latest
    needs: deploy
    if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' }}
    steps:
      - uses: actions/checkout@v4

      - name: Update Documentation
        run: |
          # Your script to update documentation goes here
          echo "Documentation updated on branch ${{ github.ref }}"

      - name: Commit and push if necessary
        run: |
          git config --global user.email "mileswilson@fractalfrissons.com"
          git config --global user.name "ScribeofSources"
          git add -A
          git commit -m "Update documentation" || exit 0  # This will not fail if there's nothing to commit
          git push
